apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-rest-log-deployment
spec:
  selector:
    matchLabels:
      app: spring-rest-log
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-rest-log
    spec:
      containers:
      - name: spring-rest-log
    # enter the path to your image, be sure to include the correct region prefix
        image: iad.ocir.io/apacaseanset01/epdemo/spring_rest_log:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
    # enter the name of the secret you created
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: spring-rest-service-log
spec:
  ports:
  - name: admin
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-rest-log
  type: LoadBalancer
